### ISSUE TITLE
Consider bumping up stack LTS to newer version

### ISSUE THREAD

**Issue by chshersh** [bollu/teleport#7]
With `lts-3.2` from `2015-08-24` I'm kinda scared to install this tool with `stack` in 2017. Bumping up LTS to something rather new, like current one — `lts-8.19` from `2017-06-18` makes it easier to install. Because nobody wants to store `lts-3.2` cache in his home directory... And new versions of libraries also can increase tool quality (probably).

**Comment by bollu** [comment]
haha, fair point. Could you send me a PR that does this, if possible? `:)`

**Comment by chshersh** [comment]
@bollu Yes, I can :)
